### ISSUE TITLE
Images not Loading

### ISSUE THREAD

**Issue by Sid-2002** [2anki/server#629]
When I convert from Notion2Anki using HTML, the images do not load and are replaced by a PNG icon. Please help!

**Comment by aalemayhu** [comment]
Hei @Sid-2002

Have you tried exporting again? We have experienced before that Notion produces corrupt zip files or it's missing assets if the export is big enoug or has sub pages.

Can you share the page you uploaded? I need a way to reproduce the issue on my machine so I can debug. Here is a service you can use to send me your file https://wetransfer.com/ 

My email addresse is alexander@alemayhu.com

**Comment by aalemayhu** [comment]
@Sid-2002 courtesy, ping. Are you still experiencing issues with images?

**Comment by pipma** [comment]
hi sir, i still have that problem. and unsure what is the cause

**Comment by pipma** [comment]
![DB60648E-4162-48C7-A166-4133706DA831](https://user-images.githubusercontent.com/108377803/176334639-7327bfbf-7b41-4943-b41c-1d8a28d2f7e6.jpeg)
![E1FBB18E-5B89-4ACB-A851-ECC5B4FD978A](https://user-images.githubusercontent.com/108377803/176334649-cfe16572-a111-4863-b9c5-5dc476dd4522.png)

the first picture is on my mobile ankidroid
the second picture from my ipad anki

**Comment by aalemayhu** [comment]
@Sid-2002 Thank you for following up. Can you export the APKG and send it to me via email alexander@alemayhu.com?

**Comment by pipma** [comment]
hi sir, i have sent the required file to you.

2) what i see to correct this error is that, i need to download on both device the apkg file. thus i can get all the image
3) if i just download at one device and sync it, it will get this error
4) thanl you for your followup sir

**Comment by aalemayhu** [comment]
@pipma I think there was a bug with the filename from 2anki.net. It should now be resolved, can you try to reproduce the issue in 15 minutes (I deployed a fix recently)? I will also send you a follow-up email. Thank you!

**Comment by pipma** [comment]
his sir, i ill try

before this, i tell u that i download and install on 2 devices and then sync. actually that too didnt work. as anki will try to produce another file with + sign after it. 

because right now i am on 3 devices. so its quite hectic to sync and download the file. hehe but ill try sir. ty for your followup

**Comment by aalemayhu** [comment]
Great, let me know how it goes 👍🏽

**Comment by pipma** [comment]
Hey Sir, ive try your technique before and now its working fine

1) after download and install anki at one device, ill sync it across device
2) then if the error appear, i immediately check the image, or force one
direction only
3) right now all of it seems correct
4) if any other issues persist in the future I'll let you know
5) hey thanks for developing and creating anki sir
6) i hope i knew since kindergarten about this ahahaha
